services:
    db:
        image: postgres:16
        container_name: restaurant-db
        restart: always
        environment:
            POSTGRES_DB: restaurant_tec
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: curso
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data

volumes:
    db_data:
